import 'package:cars_manager/features/analytics/domain/export_service.dart';
import 'package:cars_manager/models/car.dart';
import 'package:cars_manager/models/fine_data.dart';
import 'package:cars_manager/models/fuel_entry.dart';
import 'package:cars_manager/models/inspection_data.dart';
import 'package:cars_manager/models/insurance_data.dart';
import 'package:cars_manager/models/repair_data.dart';
import 'package:cars_manager/models/tax_data.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ExportService CSV backups', () {
    test('round trips cars and entries generated by the app', () {
      final cars = [
        Car(
          id: 'car-1',
          name: 'Daily, Driver',
          model: 'Model "S"',
          manufacture: 'Tesla',
          yearOfManufacture: 2024,
          licensePlate: 'CM 001',
          fuelType: FuelType.electric,
          fuel: [
            FuelEntry(
              fuelType: FuelType.electric,
              liters: 45,
              totalCost: 18.5,
              pricePerLiter: 0.41,
              date: DateTime(2026, 1, 2),
            ),
          ],
          insuranceDatas: [
            InsuranceData(
              insuranceCompany: 'ACME Insurance',
              policyNumber: 'POL-1',
              startDate: DateTime(2026),
              endDate: DateTime(2027),
              premiumAmount: 800,
            ),
          ],
          inspectionDatas: [
            InspectionData(
              date: DateTime(2026, 2, 3),
              isPassed: true,
              amount: 75,
              mileage: 12000,
            ),
          ],
          taxDatas: [TaxData(date: DateTime(2026, 3, 4), amount: 220)],
          repairDatas: [
            RepairData(
              date: DateTime(2026, 4, 5),
              amount: 140,
              description: 'Cabin filter',
            ),
          ],
          fineDatas: [
            FineData(
              date: DateTime(2026, 5, 6),
              amount: 45,
              type: FineType.parking,
            ),
          ],
        ),
      ];

      final csv = ExportService.carsToCSV(cars);
      final imported = ExportService.carsFromCSV(csv);

      expect(imported, hasLength(1));
      expect(imported.single.name, 'Daily, Driver');
      expect(imported.single.model, 'Model "S"');
      expect(imported.single.fuel.single.totalCost, 18.5);
      expect(imported.single.insuranceDatas.single.policyNumber, 'POL-1');
      expect(imported.single.inspectionDatas.single.mileage, 12000);
      expect(imported.single.taxDatas.single.amount, 220);
      expect(imported.single.repairDatas.single.description, 'Cabin filter');
      expect(imported.single.fineDatas.single.type, FineType.parking);
    });

    test('rejects CSV that was not generated by the app', () {
      expect(
        () => ExportService.carsFromCSV('Car,Type,Date,Amount\nA,Fuel,2026,1'),
        throwsFormatException,
      );
    });
  });
}
