include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    unnecessary_import: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/l10n/app_localizations*.dart

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    use_super_parameters: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    avoid_redundant_argument_values: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    use_string_buffers: true
    always_use_package_imports: true
    no_leading_underscores_for_local_identifiers: true
