name: cars_manager
description: "Cars Manager — the smart way to manage your vehicles. Track fuel consumption, maintenance, insurance, taxes, repairs, fines, and get reminders before due dates."

publish_to: 'none' 

version: 2.0.3+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  country_flags: ^4.1.1
  fl_chart: ^1.0.0
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  crop_your_image: ^2.0.0
  web: ^1.1.0
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.0
  share_plus: ^10.1.4
  flutter_animate: 4.5.0
  add_2_calendar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.1.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.1
  json_serializable: ^6.8.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/
    
lint_staged:
  'lib/**.dart': dart format --fix && dart fix --apply
