name: cars_manager
description: "CarsManager — the smart way to manage your vehicles. Track fuel consumption, maintenance, insurance, taxes, repairs, fines, and get reminders before due dates."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.5
  google_fonts: ^8.1.0
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  country_flags: ^4.1.1
  fl_chart: ^1.0.0
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  crop_your_image: ^2.0.0
  web: ^1.1.0
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/
    
lint_staged:
  'lib/**.dart': dart format --fix && dart fix --apply